apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account
secrets:
- name: builder-secret
imagePullSecrets:
- name: builder-secret
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persisent-volume-claim-name
spec:
  storageClassName: "hostpath"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: kpack.io/v1alpha1
kind: Build
metadata:
  name: spring-boot-multi-arch-build
spec:
  tags:
  - franktylerva/spring-boot-multi-arch-bp
  serviceAccount: service-account
  builder:
    image: gcr.io/paketo-buildpacks/builder:base
    imagePullSecrets: 
    - name: builder-secret  
  cacheName: persisent-volume-claim-name
  source:
    git:
      url: https://github.com/franktylerva/spring-boot-multi-arch.git
      revision: main
  env:
  - name: "JAVA_BP_ENV"
    value: "value"
  resources:
    requests:
      cpu: "0.25"
      memory: "128M"
    limits:
      cpu: "0.5"
      memory: "256M"