apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-boot-multi-arch
  name: spring-boot-multi-arch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-multi-arch
  strategy: {}
  template:
    metadata:
      labels:
        app: spring-boot-multi-arch
    spec:
      containers:
      - image: franktylerva/spring-boot-multi-arch
        name: spring-boot-multi-arch
        resources: {}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-boot-multi-arch
  name: spring-boot-multi-arch
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot-multi-arch
  type: LoadBalancer
